# Generated by Django 5.2.5 on 2025-08-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['super_category__name', 'name', 'slug'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.category',),
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Суперкатегория',
                'verbose_name_plural': 'Суперкатегории',
                'ordering': ['name', 'slug'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.supercategory', verbose_name='Суперкатегория'),
        ),
    ]
