# Generated by Django 5.2.5 on 2025-09-02 13:54

import django.db.models.deletion
import product.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сета')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание сета')),
                ('image', models.ImageField(upload_to=product.utilities.get_image_filename, verbose_name='Изображение сета')),
                ('total_price', models.FloatField(default=0, verbose_name='Общая цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.set', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'Товар в комплекте',
                'verbose_name_plural': 'Товары в комплекте',
            },
        ),
        migrations.AddField(
            model_name='set',
            name='products',
            field=models.ManyToManyField(through='product.SetProduct', to='product.product', verbose_name='Товары'),
        ),
    ]
