# Generated by Django 5.2.5 on 2025-09-03 16:32

import django.db.models.deletion
from django.db import migrations, models

def set_initial_is_supercategory(apps, schema_editor):
    Category = apps.get_model('product', 'Category')
    Category.objects.filter(super_category__isnull=True).update(is_supercategory=True)
    Category.objects.filter(super_category__isnull=False).update(is_supercategory=False)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_set_product_quantity_setproduct_set_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_supercategory',
            field=models.BooleanField(default=False, verbose_name='Суперкатегория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_supercategory': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.supercategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.RunPython(set_initial_is_supercategory, migrations.RunPython.noop),
    ]
