# Generated by Django 5.2.5 on 2025-09-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_is_supercategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Габариты (мм)')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Объем (мл)')),
                ('warranty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гарантия')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристики товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
    ]
