# Generated by Django 5.2.5 on 2025-09-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDescriptionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('select', 'Выбор из списка')], max_length=20, verbose_name='Тип поля')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Опции')),
            ],
            options={
                'verbose_name': 'Динамическое поле',
                'verbose_name_plural': 'Динамические поля',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_type', models.CharField(max_length=200, verbose_name='Тип описания')),
                ('content', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Описание товара',
                'verbose_name_plural': 'Описания товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductDynamicDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.dynamicdescriptionfield', verbose_name='Поле')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Динамическое описание товара',
                'verbose_name_plural': 'Динамические описания товаров',
            },
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
