# Generated by Django 5.2.5 on 2025-09-07 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_dynamicdescriptionfield_productdescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/<function get_image_filename at 0x000001A60B60EC00>', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='product/<function get_image_filename at 0x000001A60B60EC00>', verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='hitproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='product.product', verbose_name='Хит товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.subcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/<function get_image_filename at 0x000001A60B60EC00>', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productdynamicdescription',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_descriptions', to='product.dynamicdescriptionfield', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='productdynamicdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_descriptions', to='product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='set',
            name='products',
            field=models.ManyToManyField(related_name='sets', through='product.SetProduct', to='product.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_products', to='product.set', verbose_name='Комплект'),
        ),
    ]
