# Generated by Django 5.2.5 on 2025-09-17 14:22

import product.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_image_alter_additionalimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=product.utilities.get_image_filename_product, verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.utilities.get_image_filename_category, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.utilities.get_image_filename_product, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.ImageField(upload_to=product.utilities.get_image_filename_set, verbose_name='Изображение сета'),
        ),
    ]
