# Generated by Django 5.2.5 on 2025-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_additionalimage_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Скидка в процентах'),
        ),
    ]
