# Generated by Django 5.2.5 on 2025-09-19 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_set_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hitproduct',
            options={'verbose_name': 'Хит', 'verbose_name_plural': 'Хиты'},
        ),
        migrations.AddField(
            model_name='hitproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='hitproduct',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='HitSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('set_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='product.set', verbose_name='Хит комплект')),
            ],
            options={
                'verbose_name': 'Хит',
                'verbose_name_plural': 'Хиты',
                'abstract': False,
            },
        ),
    ]
