# Generated by Django 5.2.5 on 2025-09-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_hitproduct_options_hitproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hitproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Хит товара', 'verbose_name_plural': 'Хиты товаров'},
        ),
        migrations.AlterModelOptions(
            name='hitset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Хит комплекта', 'verbose_name_plural': 'Хиты комплектов'},
        ),
        migrations.RemoveField(
            model_name='hitproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='hitset',
            name='slug',
        ),
    ]
