# Generated by Django 5.2.5 on 2025-09-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_model_image'),
        ('product', '0012_alter_hitproduct_options_alter_hitset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.model', verbose_name='Модель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
