# Generated by Django 5.2.5 on 2025-10-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_model_image'),
        ('product', '0013_productapplicability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productapplicability',
            options={'verbose_name': 'Применяемость', 'verbose_name_plural': 'Применяемость'},
        ),
        migrations.RemoveField(
            model_name='productapplicability',
            name='model',
        ),
        migrations.AlterField(
            model_name='productapplicability',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicability', to='product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productapplicability',
            name='model',
            field=models.ManyToManyField(related_name='applicability_products', to='garage.model', verbose_name='Модель'),
        ),
    ]
