# Generated by Django 5.2.5 on 2025-10-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_productreview_setreview_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='setreview',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Рейтинг'),
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
