# Generated by Django 5.2.5 on 2025-10-12 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0006_alter_answer_unique_together_answer_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'user'), name='unique_answer_per_question'),
        ),
    ]
