# Generated by Django 5.2.5 on 2025-09-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_garage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной автомобиль')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.model', verbose_name='Модель автомобиля')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='garage.garage', verbose_name='Гараж')),
            ],
        ),
        migrations.AddField(
            model_name='garage',
            name='models',
            field=models.ManyToManyField(through='garage.UserCar', through_fields=('garage', 'car_model'), to='garage.model', verbose_name='Модели автомобилей'),
        ),
    ]
