# Generated by Django 5.2.5 on 2025-09-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_usercar_garage_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercar',
            options={'verbose_name': 'Автомобиль пользователя', 'verbose_name_plural': 'Автомобили пользователя'},
        ),
    ]
