# Generated by Django 5.2.5 on 2025-09-27 11:15

import product.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_usercar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.utilities.get_image_filename_model_car, verbose_name='Изображение модели'),
        ),
    ]
