# Generated by Django 5.2.5 on 2025-10-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercar',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='garage.model', verbose_name='Модель автомобиля'),
        ),
    ]
